// src/routes/ingredients-group.svelte
<script lang="ts">
  import type { IngredientsGroup } from '$lib/types'
  import Ingredient from './ingredient.svelte'

  export let group: IngredientsGroup
  export let showIngredientsHeading: boolean
  export let defaultServings: number
  export let servings: number
</script>

{#if group.ingredients.length > 0}
  {#if showIngredientsHeading}
    <h4>{group.name}</h4>
  {/if}
  <div>
    {#each group.ingredients as ingredient}
      <Ingredient {ingredient} {defaultServings} {servings} />
    {/each}
  </div>
{/if}

<style>
  div {
    margin-left: 0;
  }
</style>

// src/components/IngredientsGroupComponent.tsx
import React from 'react';
import styled from 'styled-components';
import { IngredientsGroup } from '../interfaces/Recipe';
import IngredientComponent from './IngredientComponent';

interface IngredientsGroupProps {
  group: IngredientsGroup;
  servings: number;
  defaultServings: number;
  shouldShowHeading: boolean;
}

export default function IngredientsGroupComponent({
  group,
  servings,
  defaultServings,
  shouldShowHeading = false,
}: IngredientsGroupProps) {
  if (!(group.ingredients.length > 0)) return null;

  return (
    <>
      {shouldShowHeading && <h3>{group.name}</h3>}
      <IngredientsListStyled>
        {group.ingredients.map((ingredient, index) => (
          <IngredientComponent
            ingredient={ingredient}
            servings={servings}
            defaultServings={defaultServings}
            key={index}
          />
        ))}
      </IngredientsListStyled>
    </>
  );
}

const IngredientsListStyled = styled('ul')`
  margin-left: 0;
`;
